version: '3'
services:
  mongo:
    container_name: mongo_container
    image: "mongo:3.6.20-stretch"
    ports:
      - "27017:27017"
    networks:
      - dashboardnetwork
    ulimits:
      nofile: 65536
      # memlock:
      #   soft: -1
      #   hard: 1
    volumes:
      - mongodata:/data/db
  teamservice:
    container_name: teamservice
    image: awconstable/teamservice
    depends_on:
      - mongo
    networks:
      - dashboardnetwork
    ports:
      - "8082:8080"
    environment:
      - spring_data_mongodb_host=mongo_container
      - spring_data_mongodb_port=27017
      - spring_data_mongodb_database=team
volumes:
  mongodata:
networks:
  dashboardnetwork:
