version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

workflows:
  build-deploy:
    jobs:
      - unit-test:
          filters:
            tags:
              only: /.*/
      - publish-docker:
          requires:
            - unit-test
          filters:
            tags:
              only: /.*/
            branches:
              only: master

jobs:
  unit-test:
    docker:
      - image: circleci/openjdk:11-jdk-stretch-browsers

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "web/build.gradle" }}

      - run: ./gradlew test jacocoTestReport
      
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "web/build.gradle" }}
      - store_test_results:
          path: web/build/test-results/test
      - store_artifacts:
          path: web/build/test-results/test
          when: always
      - store_artifacts:
          path: web/build/reports/jacoco
      - codecov/upload:
          file: web/build/reports/jacoco/test/jacocoTestReport.xml

  publish-docker:
    docker:
      - image: circleci/openjdk:11-jdk-stretch-browsers
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "web/build.gradle" }}
      - restore_cache:
          key: v1-gradle-jib-cache-{{ checksum "build.gradle" }}-{{ checksum "web/build.gradle" }}
      - run:
          name: Setup Docker Hub Credentials
          command: |
            mkdir ~/.docker \
            cat config.json | sed 's/_AUTH_TOKEN_/$DOCKER_HUB_TOKEN/g' > ~/.docker/config.json
      - run:
          name: If we're building a tag, set the version to that of the tag
          command: |
            if [ -n "$CIRCLE_TAG" ]; \
            then \
              ./gradlew final; \
            fi
      - deploy:
          name: Publish Docker image with Jib
          command: |
            if [ -n "$CIRCLE_TAG" ]; \
            then \
                LATEST_DOCKER_TAG=-Djib.to.tags=latest; \
            fi; \
            ./gradlew jib \
               $LATEST_DOCKER_TAG
      - save_cache:
          paths:
            - web/build/jib-cache
          key: v1-gradle-jib-cache-{{ checksum "build.gradle" }}-{{ checksum "web/build.gradle" }}