version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

workflows:
  build-deploy:
    jobs:
      - unit-test:
          filters:
            tags:
              only: /.*/
      - publish-docker:
          requires:
            - unit-test
          filters:
            tags:
              only: /.*/
            branches:
              only: master

jobs:
  unit-test:
    machine:
        image: ubuntu-2004:202010-01

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "web/pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:resolve-plugins dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "web/pom.xml" }}

      # run tests!
      - run: mvn test integration-test verify
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
            mkdir -p ~/test-results/jacoco/
            find . -type f -regex ".*/target/jacoco-reports/.*xml" -exec cp {} ~/test-results/jacoco/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results
      - store_artifacts:
          path: web/target/jacoco-reports
      - codecov/upload:
          file: ~/test-results/jacoco/jacoco.xml

  publish-docker:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "web/pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - run: cp .mvn/wrapper/settings.xml ~/.m2/settings.xml

      - run: echo "<settingsSecurity><master>${maven_security_master}</master></settingsSecurity>" > ~/.m2/settings-security.xml
      - run:
          name: If we're building a tag, set the version to that of the tag
          command: |
            if [ -n "$CIRCLE_TAG" ]; \
            then \
              mvn versions:set -DnewVersion=${CIRCLE_TAG}; \
            fi
      - deploy:
          name: Publish Docker image with Jib
          command: |
            if [ -n "$CIRCLE_TAG" ]; \
            then \
                LATEST_DOCKER_TAG=-Djib.to.tags=latest; \
            fi; \
            mvn compile jib:build -B -DskipTests=true \
              -Dbuild.number=${CIRCLE_BUILD_NUM} \
              -Dcommit.hash=${CIRCLE_SHA1} \
              -Dcircle.workflow.guid=${CIRCLE_WORKFLOW_ID} \
              -Dbuild.user=${CIRCLE_PROJECT_USERNAME} \
              -Dbuild.repo=${CIRCLE_PROJECT_REPONAME} \
              $LATEST_DOCKER_TAG